export interface SSLCommerzInitPayload {
    store_id: string;
    store_passwd: string;
    is_live: boolean;
    total_amount: number;
    currency: string;
    tran_id: string;
    success_url: string;
    fail_url: string;
    cancel_url: string;
    ipn_url: string;
    shipping_method: string;
    product_name: string;
    product_category: string;
    product_profile: string;
    cus_name: string;
    cus_email: string;
    cus_add1: string | null;
    cus_add2: string;
    cus_city: string;
    cus_state: string;
    cus_postcode: string;
    cus_country: string;
    cus_phone: string;
    cus_fax: string;
    ship_name: string;
    ship_add1: string;
    ship_add2: string;
    ship_city: string;
    ship_state: string;
    ship_postcode: number;
    ship_country: string;
}

export interface SSLValidationPayload {
    tran_id: string;
    val_id: string;
    amount: string;
    card_type: string;
    store_amount: string;
    card_no: string;
    bank_tran_id: string;
    status: 'VALID' | 'FAILED' | 'CANCELLED' | 'UNATTEMPTED' | 'EXPIRED';
    tran_date: string;
    error: string;
    currency: string;
    card_issuer: string;
    card_brand: string;
    card_sub_brand: string;
    card_issuer_country: string;
    card_issuer_country_code: string;
    store_id: string;
    verify_sign: string;
    verify_key: string;
    verify_sign_sha2: string;
    currency_type: string;
    currency_amount: string;
    currency_rate: string;
    base_fair: string;
    value_a: string;
    value_b: string;
    value_c: string;
    value_d: string;
    subscription_id: string;
    risk_level: string;
    risk_title: string;
}

export interface SSLValidationResponse {
    status: 'VALID' | 'VALIDATED' | 'INVALID_TRANSACTION';
    tran_date: string;
    tran_id: string;
    val_id: string;
    amount: string;
    store_amount: string;
    currency: string;
    bank_tran_id: string;
    card_type: string;
    card_no: string;
    card_issuer: string;
    card_brand: string;
    card_category: string;
    card_sub_brand: string;
    card_issuer_country: string;
    card_issuer_country_code: string;
    currency_type: string;
    currency_amount: string;
    currency_rate: string;
    base_fair: string;
    value_a: string;
    value_b: string;
    value_c: string;
    value_d: string;
    emi_instalment: string;
    emi_amount: string;
    emi_description: string;
    emi_issuer: string;
    account_details: string;
    risk_title: string;
    risk_level: string;
    discount_percentage: string;
    discount_amount: string;
    discount_remarks: string;
    APIConnect: string;
    validated_on: string;
    gw_version: string;
    offer_avail: number;
    card_ref_id: string;
    isTokeizeSuccess: number;
    campaign_code: string;
}
